# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Creates a JavaDoc
      run: javadoc -d /home/runner/work/Laboratorul8I-C/Laboratorul8I-C/myjavadoc -sourcepath /home/runner/work/Laboratorul8I-C/src/*
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: myartifact
        # Destination path
        path: /home/runner/work/Laboratorul8I-C/Laboratorul8I-C/dist/lab8.jar
